---
# tasks file for svr-dnsmasq
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: Restart dnsmasq

- name: Start dnsmasq service
  service:
    name: dnsmasq
    state: started
    enabled: true
